### ISSUE TITLE
运行抛异常 threads can only be started once

### ISSUE THREAD

**Issue by pertgame** [mmmaaaggg/HuobiFeeder#1]
按照说明装好环境后再centos上运行，数据库初始化简历都成功了，之后会反复抛出异常：threads can only be started once

运行日志如下：

2018-07-24 15:31:52,294 INFO HuoBi service.py.on_open:95|<订阅>初始化订阅完成
2018-07-24 15:31:52,636 INFO HuoBi service.py.on_message:56|<订阅>Topic:market.btcusdt.kline.1min订阅成功 Time:2018-07-24 15:31:52.399000 ##
2018-07-24 15:31:52,636 INFO HuoBi service.py.on_message:56|<订阅>Topic:market.btcusdt.kline.60min订阅成功 Time:2018-07-24 15:31:52.400000 ##
2018-07-24 15:31:52,637 INFO HuoBi service.py.on_message:56|<订阅>Topic:market.btcusdt.kline.1day订阅成功 Time:2018-07-24 15:31:52.400000 ##
2018-07-24 15:31:52,637 INFO HuoBi service.py.on_message:56|<订阅>Topic:market.bchusdt.kline.1min订阅成功 Time:2018-07-24 15:31:52.400000 ##
2018-07-24 15:31:52,637 INFO HuoBi service.py.on_message:56|<订阅>Topic:market.bchusdt.kline.60min订阅成功 Time:2018-07-24 15:31:52.400000 ##
2018-07-24 15:31:52,638 INFO HuoBi service.py.on_message:56|<订阅>Topic:market.bchusdt.kline.1day订阅成功 Time:2018-07-24 15:31:52.400000 ##
2018-07-24 15:31:52,638 INFO HuoBi service.py.on_message:56|<订阅>Topic:market.ethusdt.kline.1min订阅成功 Time:2018-07-24 15:31:52.400000 ##
2018-07-24 15:31:52,638 INFO HuoBi service.py.on_message:56|<订阅>Topic:market.ethusdt.kline.60min订阅成功 Time:2018-07-24 15:31:52.400000 ##
2018-07-24 15:31:52,639 INFO HuoBi service.py.on_message:56|<订阅>Topic:market.ethusdt.kline.1day订阅成功 Time:2018-07-24 15:31:52.400000 ##
2018-07-24 15:31:52,639 INFO HuoBi service.py.on_message:56|<订阅>Topic:market.etcusdt.kline.1min订阅成功 Time:2018-07-24 15:31:52.400000 ##
2018-07-24 15:31:52,928 ERROR HuoBi handler.py.run:48|<Handler>-DB[md_min1_tick_bc] exception:threads can only be started once
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/huobitrade/handler.py", line 44, in run
    self.handle(msg)
  File "/home/pub/HuobiFeeder/huobifeeder/backend/handler.py", line 91, in handle
    self.save_md(data)
  File "/usr/local/python3/lib/python3.6/site-packages/prodconpattern/__init__.py", line 40, in _call
    self.start()
  File "/usr/local/python3/lib/python3.6/threading.py", line 842, in start
    raise RuntimeError("threads can only be started once")
RuntimeError: threads can only be started once

**Comment by mmmaaaggg** [comment]
这个bug已经修复了
此前希望作为子进程启动的，后来发现不行，因此改回来了
